# Generated by Django 4.1.5 on 2023-03-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('discription', models.TextField(max_length=300)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('total_cost', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(to='app.product')),
            ],
        ),
    ]
