# Generated by Django 4.1.7 on 2023-03-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_country_user_producer_user_product_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(default=1, to='app.product'),
        ),
    ]
