# Generated by Django 4.1.7 on 2023-03-29 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_order_products_alter_producer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(default=122, on_delete=django.db.models.deletion.CASCADE, to='app.producer'),
        ),
    ]
