# Generated by Django 4.1.7 on 2023-03-29 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='all_cost',
            field=models.PositiveIntegerField(default=111),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.producer'),
        ),
    ]
