# Generated by Django 4.1.5 on 2023-03-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_book', models.CharField(help_text='Title book', max_length=20)),
                ('author', models.CharField(help_text='Author', max_length=20)),
                ('annotations', models.CharField(help_text='Annotations', max_length=20)),
            ],
        ),
    ]
